### ISSUE TITLE
ivysilani nefunguje "varovani pro mladistve"

### ISSUE THREAD

**Issue by jurafxp** [StepanOrt/kodi-addons#5]
Po spusteni videa s "varovanim pro mladistve" se stream prerusi (napr. porad "Kmeny")

**Comment by Jiri-Kremser** [comment]
stejny problem mam

**Comment by StepanOrt** [comment]
Doplněk je nyní přesunut do Kodi CZ/SK, kde je problém opraven

**Comment by Jiri-Kremser** [comment]
diky
